package javaoutputquestions;

public class ExceptionHandling2 {
    public static void main(String[] args){
        /*
        * Below was the code in DRUVA online test
        *
        * Tell the output of below code?
        *
        * Answer: compile error
        *
        * */

        /*try{
            try{
                throw 100;
            }catch (int i){
                System.out.println("inside catch block");
            }
        }catch (int i){
            System.out.println("outside catch block");
        }*/

        return;
    }
}
